administrator manage resources
manatee-project/manatee pull request #20
Opened 2024-11-05 12:08 UTC by privacywill

Project administrator create resources for each developer, as a result the developers only need to build and push the image and deploy. As a result, the developers only require `Artifact registry writer` role in gcp project.

# Changes

* Rename the `reousrce/gcp` to `resource/global`.
* Rename the `reousrce/kubernetes` to `resource/developer-specific`.
* Add a script `push_image.sh` to push the image. Because the repository parameters is too long in bazel oci_push cmdline. 
* Create developer specific database and db account.  Move it to `resource/developer-specific`.

# Testing

Manual end-to-end testing.

2024-11-05 22:41 UTC, dayeol commented
can you try to use `multirun` instead of a bash script?
See #7

2024-11-06 18:44 UTC, dayeol requested changes

2024-11-07 02:16 UTC, privacywill commented on deployment/jupyterhub/deploy.sh
> +helm_name="jupyterhub-helm-$namespace"
Deploying the jupyterhub through helm creates a global kubernetes role. If we use the same `helm_name` for every developers even if they belongs to different namespaces, the global role still has conflicts. So I add namespace to the `helm_name`

2024-11-07 03:44 UTC, privacywill commented on README.md
> +./push_image.sh --namespace=dcr-namespace
done

2024-11-07 03:45 UTC, privacywill commented on resources/deployment/db_account.tf
> +}
OK

2024-11-07 07:16 UTC, privacywill commented on resources/deployment/apply.sh
> +cat << EOF > backend.tf
done

2024-11-08 05:25 UTC, dayeol commented
made small changes by myself!

2024-11-08 05:26 UTC, dayeol approved these changes
lgtm!

2024-11-08 06:11 UTC, merged